### ISSUE TITLE
Enrichment service using templates 4, 5 and 7 - Response 500

### ISSUE THREAD

**Issue by borriellom** [freme-project/e-Link#19]
Using one of  the templates listed in the object, the enrichment service always returns  a 500 response.
Maybe it is due to problems at sparql endpoints:
Templates [4](https://github.com/freme-project/technical-discussion/wiki/Broker-API-Calls#sparql-endpoint-httplinkedgeodataorgvsnorql) and [7](https://github.com/freme-project/technical-discussion/wiki/Broker-API-Calls#sparql-endpoint-httplinkedgeodataorgvsnorql-1): http://linkedgeodata.org/vsnorql 
Template [5](https://github.com/freme-project/technical-discussion/wiki/Broker-API-Calls#sparql-endpoint-httpeuropeanaontotextcomsparql): http://europeana.ontotext.com/sparql

*Example*

**Request**
POST  URL: http://api-dev.freme-project.eu/current/e-link/documents/?outformat=json-ld&templateid=4
HEADER "Content-Type" = "text/turtle"

**Input Text**
```
@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .
<http://127.0.0.1:9995/spotlight#char=0,15>
        a                     nif:Context , nif:Sentence , nif:RFC5147String ;
        nif:beginIndex        "0" ;
        nif:endIndex          "15" ;
        nif:isString          "This is Berlin." ;
        nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,15> .

<http://127.0.0.1:9995/spotlight#char=8,14>
        a                     nif:Word , nif:RFC5147String ;
        nif:anchorOf          "Berlin" ;
        nif:beginIndex        "8" ;
        nif:endIndex          "14" ;
        nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,15> ;
        itsrdf:taIdentRef     <http://dbpedia.org/resource/Berlin> .
```

**Response**
Error 500

**Comment by m1ci** [comment]
this issue can be closed - the issue is covered by https://github.com/freme-project/e-Link/issues/40 and https://github.com/freme-project/e-Link/issues/39
