### ISSUE TITLE
migrate templates to linked data fragments endpoints

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Link#29]
Currently, we face with performance and availability issues of the SPARQL endpoints which are consumed by the templates. As solution, we consider moving templates to LDF endpoints, which use following datasets:
- DBpedia
- GeoNames
- LinkedGeoData
- EventMedia

If possible, also:
- VIAF
- ORCID

**Comment by m1ci** [comment]
@jnehring we need additional flag in the template storage model - whether the template is sparql or ldf. Since you did the persistence, can you please add this flag? I can provide the code for querying LDF endpoint in the DataEnricher

**Comment by jnehring** [comment]
I created #46 to update the template model.

**Comment by m1ci** [comment]
ok, thanks!

**Comment by m1ci** [comment]
this has be done.
The templates now can be run against SPARQL or LDF endpoint.

A template can be created by submitting them as JSON which has the following structure:
```
{
   "query" : "the sparql query",
   "endpoint" : "the endpoint URL",
   "label" : "the title of the template",
   "description":"a description of the template",
   "endpoint-type":"the endpoint type, sparql or ldf"
 }
```

A template can be submitted and created using the following cURL command:

    curl -v "http://api-dev.freme-project.eu/current/e-link/templates?visibility=public&outformat=json&token=YOUR_TOKEN" -H "Content-Type: application/json" -d @template.json

Note: you should specify the visibility of the template using the `visibility` parameter.

Upon successful creation, in the response the client receives representation of the template including the ID. Example of such response:

```
{
  "id" : 302,
  "owner" : {
    "name" : "milan",
    "role" : "ROLE_USER"
  },
  "visibility" : "PUBLIC",
  "endpoint" : "http://live.dbpedia.org/sparql",
  "query" : "PREFIX dbpedia: <http://dbpedia.org/resource/> PREFIX dbo: <http://dbpedia.org/ontology/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> CONSTRUCT {   ?museum <http://xmlns.com/foaf/0.1/based_near> <@@@entity_uri@@@> . } WHERE {  <@@@entity_uri@@@> geo:geometry ?citygeo .  OPTIONAL { ?museum rdf:type dbo:Museum . }  ?museum geo:geometry ?museumgeo .  FILTER (<bif:st_intersects>(?museumgeo, ?citygeo, 50)) } LIMIT 10",
  "label" : "the title of the template",
  "description" : "a description of the template",
  "type" : "SPARQL"
}
```

A template can be used for enrichment using the following cURL command:

    curl -v "http://api-dev.freme-project.eu/current/e-link/documents?templateid=302&outformat=turtle&token=YOUR_TOKEN" -H "Content-Type: text/turtle" -d @nif.ttl

**Comment by m1ci** [comment]
closing the issue, you can test the LDF templates using the instruction in the previous comment.
