### ISSUE TITLE
[idea] Enrich with multiple templates

### ISSUE THREAD

**Issue by ghsnd** [freme-project/e-Link#32]
An idea for a future implementation: now it is possible to enrich a document using only 1 template at a time. I can imagine that one wants documents enriched with 2 or more templates, e.g. "the birth date of writers" occurring in the text and also with "the country of places" occurring.

The request would become something like

    .../e-link/documents?templateid=3,5,21

**Comment by m1ci** [comment]
> "the birth date of writers" occurring in the text and also with "the country of places" occurring.

So you write a template which will enrich with that info.

The idea of being able to perform enrichment with several templates might seem at first sight useful BUT:
- the feature you are asking can be done with `pipelines` - this is one reason why they exist
- having one template which will be used to enrich with the same info is faster
- adding more complexity to the code
- no real innovation - we would rather focus on more important and innovative `domain specific` tasks

Also, you can realize this feature with unix pipes. See the example bellow:

    curl "http://api-dev.freme-project.eu/current/e-link/documents?templateid=302&outformat=turtle&token=YOUR_TOKEN" -H "Content-Type: text/turtle" -d @nif.ttl  | curl -v "http://api-dev.freme-project.eu/current/e-link/documents?templateid=301&outformat=turtle&token=YOUR_TOKEN" -H "Content-Type: text/turtle" -d @-

**Comment by jnehring** [comment]
I also think that we can use a pipeline for this, or a special template or the user has to do two api calls. Lets not make this feature more complicated then it is.

I close the issue. @ghsnd when you still have a need for this feature you can reopen and we continue discussing it.
