### ISSUE TITLE
Update e-Link persistence

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#43]
* Include FREMECommon dependency in e-Link
* Exchange Template Database in e-Link

**Comment by ArneBinder** [comment]
implemented.

**Comment by m1ci** [comment]
@ArneBinder, @jnehring is the persistence already committed to the master branch? If not, can you please do it?

**Comment by m1ci** [comment]
... noticed template-persistence branch in e-link and coversion-services projects.

**Comment by jnehring** [comment]
It is merged in the master branch in (this package of FREMECommon](https://github.com/freme-project/FREMECommon/tree/master/src/main/java/eu/freme/common/persistence). But there is bug #44 which should be fixed tomorrow.

@ArneBinder please delete the old branches.

**Comment by ArneBinder** [comment]
#44 occurs only by using the broker as unauthenticated user. @m1ci it should not affect your work (I hope so). The template-persistence branch was already merged into the e-link master.

**Comment by ArneBinder** [comment]
Can we close this?

**Comment by jnehring** [comment]
I am not sure if the GET / POST / PUT / DELETE dataset endpoints work right now. @ArneBinder please test this before you close this ticket.

**Comment by jnehring** [comment]
Bug in POST template: https://github.com/freme-project/e-Link/issues/47

**Comment by ArneBinder** [comment]
checked all template endpoints, no problems found.
