### ISSUE TITLE
Re-uploading the templates to the MySQl database

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/e-Link#45]
Who should be the owner of the existing seven templates? 
Perhaps, @m1ci do you want to create an user via the [documentation-page](http://api-dev.freme-project.eu/doc/#/), then authenticate yourself via curl (this will return a json object containing a token) and re-upload the templates (also via curl, use the token as header parameter "X-Auth-Token")? 

Or we wait for [this issue](https://github.com/freme-project/Documentation/issues/85) and do it via the documentation page, but this could need some time.

Or I will create a dummy user and do this via curl. Then we would switch the owner later. In this case, please reassign to me.

**Comment by m1ci** [comment]
> Or I will create a dummy user and do this via curl. Then we would switch the owner later. In this case, please reassign to me.

Yes, will you be so kind and do that? Thanks!

Also, can you please upload also the template with ID 300.
Unfortunately, it is not available at the moment http://api-dev.freme-project.eu/current/e-link/templates/300?outformat=json but it was available with the previous document based storage.

**Comment by ArneBinder** [comment]
Ok, i will check this.

**Comment by ArneBinder** [comment]
I'v just taken a look to the templates in [the last documentation version](http://api.freme-project.eu/doc/0.3/#!/e-Link/getAllTemplates). There are more then the seven, which are documented at the doc page. Which of them should I integrate into the new db? Unfortunately I could not find one with ID 300. @m1ci do you have it anywhere else? otherwise I had to go back to an earlier commit manually and refetch them via broker calls...

**Comment by m1ci** [comment]
it was (should be) in `templates.ttl` file

**Comment by ArneBinder** [comment]
Sorry for bothering again, but I checked several previous commit states and could not find template 300. When did you added this one?

**Comment by m1ci** [comment]
On Sep 15th and later, the template was there - at the api-dev.

**Comment by m1ci** [comment]
I found it at the api-dev
```
<http://www.freme-project.eu/data/templates/300>
        a                    freme:Template ;
        rdfs:label           "DBpedia Categories" ;
        dcterms:description  "DBpedia Categories" ;
        freme:endpoint       "http://rv2622.1blu.de:8890/sparql/" ;
        freme:query          "CONSTRUCT {  <@@@entity_uri@@@> <http://purl.org/dc/terms/subject> ?category .  ?category <http://freme-project.eu/ns#info> ?info .  ?category <http://www.w3.org/2000/01/rdf-schema#label> ?label } WHERE { <@@@entity_uri@@@> <http://purl.org/dc/terms/subject> ?category .  ?category <http://freme-project.eu/ns#info> ?info . ?category <http://www.w3.org/2000/01/rdf-schema#label> ?label }" ;
        freme:templateId     "300" .
```

**Comment by ArneBinder** [comment]
thx, it is online again, the others also.
