### ISSUE TITLE
Support for RDF template formats

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#48]
The templates can be read and written using RDF or JSON. Right now only the JSON representation is up to date and contains the new fields `visibility`, `type` and `owner`. The turtle representation lacks these. Also there is no documentation for the RDF version of the template.

My suggestion is to remove the RDF version. We should remove it from broker and e-link.

@m1ci  is this ok with you? Or do you see a reason to maintain the RDF versions? I think JSON is fine and there is no need to keep both.

@ArneBinder already gathered a lot of experience with these codes and can implement this.

**Comment by m1ci** [comment]
OK, lets have JSON only.

**Comment by jnehring** [comment]
I think we will not be able to implement this within FREME 0.4. We leave this for FREME 0.5.

**Comment by m1ci** [comment]
At the moment `informat` and `outformat` are forced to JSON when manipulating with templates. RDF is not used at all.

**Comment by jnehring** [comment]
Ok I created https://github.com/freme-project/Documentation/issues/94 to note this in the documentation. I leave this issue open to take a 2nd look at the source code and do some testing.
