### ISSUE TITLE
Errors 'explore'

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Link#53]
When `endpoint-type` is incorrect, the status code is 500. However, I expect a bad request.

**Comment by m1ci** [comment]
what do you mean by incorrect?

**Comment by pheyvaer** [comment]
saying that is it LDF when it is sparql and the other way around

**Comment by m1ci** [comment]
this has been already discussed in https://github.com/freme-project/e-Link/issues/41#issuecomment-148068045 and we came to conclusion to highlight in the doc that the clients should double-check the endpoint-type and the actual endpoint URL whether they have chosen the right type.
