### ISSUE TITLE
'explore' does not support LDF

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Link#54]
with `resource` set to ` http://dbpedia.org/resource/Phil_Young_(writer)` and `endpiont` set to `http://fragments.dbpedia.org/2014/en`.

**Comment by m1ci** [comment]
it supports, it seems you did not encode the URLs
Try

    curl -X POST --header "Content-Type: application/json" --header "Accept: text/turtle" "http://api-dev.freme-project.eu/current/e-link/explore?resource=http%3A%2F%2Fdbpedia.org%2Fresource%2FPhil_Young_(writer)&endpoint=http%3A%2F%2Ffragments.dbpedia.org%2F2014%2Fen&endpoint-type=ldf"

**Comment by pheyvaer** [comment]
I didn't work using the Documentation page.

**Comment by m1ci** [comment]
@jnehring this should be fixed in the documentation page - encode URI when submitting the request.

**Comment by jnehring** [comment]
The documentation says "Please note that all parameter values submitted via the URLs query string need to be URL encoded according to RFC 3986.". I think we cannot do more.
