### ISSUE TITLE
PUT templates with non-existing ID

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Link#58]
The doc says that a new template will be created if an ID is provided of a non-existing template. However, this results in an error saying that the template with that specific ID cannot be found.

**Comment by m1ci** [comment]
If I remember well, in FREME 0.3 it was decided that this will be dropped. @jnehring right?
This means that PUT can be used only for updating resources.

If that is the case, then the documentation should be updated.

**Comment by jnehring** [comment]
I think there is no need to let users specify the IDs of templates. So we should update the documentation and remove this bit.

@josauder please change a sentence in the documentation of PUT templates:

From `Update or creates an enrichment template (if it does not exist) with specified ID.`

To `Update an enrichment template with specified ID.`
