### ISSUE TITLE
Parallel calls resulting in problems

### ISSUE THREAD

**Issue by pheyvaer** [freme-project/e-Link#59]
with the parameters given in the documentation

- explore: when doing 100 or more parallel calls (Internal Server Error)
- documents: when doing 15 or more parallel calls (Internal Server Error)
- templates: when doing 250 or more parallel calls (Internal Server Error or time out)
- templates/{templateid}: when doing 350 or more parallel cals (java.net.SocketException: Connection reset or time out)

**Comment by jnehring** [comment]
@pheyvaer can you please share the script that you used so we can reproduce the error?

**Comment by pheyvaer** [comment]
Here is a link to the JMeter file https://drive.google.com/file/d/0B-qMtkPK-unYeG1BcEhXdXotWU0/view?usp=sharing

**Comment by jnehring** [comment]
I am not so sure if we consider this as a bug report or normal behavior. What you do sounds like big data testing to me and especially the "Connection reset or time out" errors are actually correct behavior.

**Comment by m1ci** [comment]
> What you do sounds like big data / heavy load testing to me

I sounds to me like big data testing too.

**Comment by jnehring** [comment]
I think it is ok at this stage when we throw an InternalServerException when the server is overloaded. When we approach the big data topic again, maybe in FREME 0.5, then we can talk about how FREME should react on 100 calls in parallel
