### ISSUE TITLE
Create template that uses LDF

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#62]
@fsasaki wrote

http://api-dev.freme-project.eu/doc/api-doc/list-templates.html
I think we don’t have a template that shows usage of a linked data fragment endpoint - should we create one?

**Comment by m1ci** [comment]
done. Created as admin - see http://api-dev.freme-project.eu/current/e-link/templates/4447?outformat=json

NIF to enrich.
[nif-to-enrich.txt](https://github.com/freme-project/e-Link/files/27880/nif-to-enrich.txt)

cURL example:
    
    curl -v -X POST "http://api-dev.freme-project.eu/current/e-link/documents?templateid=4447&informat=turtle&outformat=turtle" -d @nif-to-enrich.txt -H "Content-Type:"

**Comment by jnehring** [comment]
Thank you!

@josauder please update the [list of templates](http://api-dev.freme-project.eu/doc/api-doc/list-templates.html). You can find title and description using http://api-dev.freme-project.eu/current/e-link/templates/4447

Somehow we lost template number 4. I double checked it was not deleted in #63 . @josauder can you please add this template? It might be possible that you cannot specify the template id. In this case just update the ID in the documentation.

**Comment by josauder** [comment]
Ok I will do that. Do you think we should take out the list of templates [here](http://api-dev.freme-project.eu/doc/api-doc/full.html#!/e-Link/getAllTemplates) because it is redundant with our dedicated list of templates page?

**Comment by josauder** [comment]
I readded the template 4  which now has id 4448. I also added the other template. Do we have any example data (for the curl call) for template 4448 (template 4)? @jnehring

**Comment by m1ci** [comment]
> Do we have any example data (for the curl call) for template 4448 (template 4)? @jnehring

example data attached with the comment https://github.com/freme-project/e-Link/issues/62#issuecomment-154009743

**Comment by m1ci** [comment]
can we close this issue?
