### ISSUE TITLE
GROUP function on our SPARQL endpoint

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#66]
Our SPARQL endpoint does not support the GROUP function. We need this for the filter queries.

@m1ci can you do something about that?

I recall from our discussions on the hackers meeting in Athens that we either have to update Virtuoso to the latest version (7.something) or we have to install a certain extension.

**Comment by m1ci** [comment]
Can you please share SPARQL query which is using GROUP BY aggregation and does not work?

**Comment by jnehring** [comment]
Endpoint: http://rv2622.1blu.de:8890/sparql
Graph IRI: http://localhost:8890/test-jan
SPARQL query:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select  (lang(?anchorOf) as ?language) (str(?anchorOf) as ?anchor) ?confidence (GROUP_CONCAT(DISTINCT ?label;SEPARATOR = ", ") AS ?new_label) (GROUP_CONCAT(DISTINCT ?uri;SEPARATOR = ", ") AS ?new_uri) where {
 ?term <http://www.w3.org/2005/11/its/rdf#term> "yes".
 ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#annotationUnit> ?annotationUnit .
  ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#anchorOf> ?anchorOf.
 ?annotationUnit rdfs:label ?label.
 ?annotationUnit <http://www.w3.org/2005/11/its/rdf#taConfidence> ?confidence.
 ?term <http://www.w3.org/2005/11/its/rdf#termInfoRef> ?uri
}
group by  ?annotationUnit ?confidence ?anchorOf ORDER by desc ( ?confidence )
```

Error message

```
Virtuoso 37000 Error SP030: SPARQL compiler, line 4: syntax error at 'GROUP_CONCAT' before '('

SPARQL query:
define sql:big-data-const 0 
#output-format:text/html
define sql:signal-void-variables 1 define input:default-graph-uri <http://localhost:8890/test-jan> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select  (lang(?anchorOf) as ?language) (str(?anchorOf) as ?anchor) ?confidence (GROUP_CONCAT(DISTINCT ?label;SEPARATOR = ", ") AS ?new_label) (GROUP_CONCAT(DISTINCT ?uri;SEPARATOR = ", ") AS ?new_uri) where {
 ?term <http://www.w3.org/2005/11/its/rdf#term> "yes".
 ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#annotationUnit> ?annotationUnit .
  ?term <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#anchorOf> ?anchorOf.
 ?annotationUnit rdfs:label ?label.
 ?annotationUnit <http://www.w3.org/2005/11/its/rdf#taConfidence> ?confidence.
 ?term <http://www.w3.org/2005/11/its/rdf#termInfoRef> ?uri
}
group by  ?annotationUnit ?confidence ?anchorOf ORDER by desc ( ?confidence )
```

**Comment by m1ci** [comment]
I've updated our Virtuoso instance to version 07.20.3212
This should fix your issue. The query is valid.

**Comment by jnehring** [comment]
Thanks. Unfortunately the query produces no output.

I also cannot open the conductor: http://rv2622.1blu.de:8890/conductor/

The query `SELECT ?s ?p ?o WHERE {?s ?p ?o}` does not produce any output as well on my graph http://localhost:8890/test-jan. Is it maybe deleted?

**Comment by m1ci** [comment]
> Thanks. Unfortunately the query produces no output.
> The query SELECT ?s ?p ?o WHERE {?s ?p ?o} does not produce any output as well on my graph http://localhost:8890/test-jan. Is it maybe deleted?

Yes, it was deleted.

> I also cannot open the conductor: http://rv2622.1blu.de:8890/conductor/

Trying to fix that now.

**Comment by m1ci** [comment]
fixed, please check.

**Comment by jnehring** [comment]
Ok thanks. I can open the conductor now. But my dataset is gone.  It is no problem that my test dataset is gone, but did we loose any other important datasets?

**Comment by m1ci** [comment]
No we did not. Actually, we have backup dumps of all our datasets. Also, everything is available via LDF too.

**Comment by jnehring** [comment]
Ok thanks for updating the endpoint
