### ISSUE TITLE
creating templates does not work

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Link#67]
Creating templates does not work in the API documentation, the error message is:

> Could not create resource: The anonymous user can not own any resource. You have to be logged in to create a resource.

How should we handled such situations?

**Comment by m1ci** [comment]
... I guess the same applies to updating templates.

**Comment by jnehring** [comment]
At the bottom of the full API documentation you can paste an API authentication token. I just tried at api-dev and it worked. Does this solve the issue?

**Comment by m1ci** [comment]
Thanks for clarification. Yes it helped. I added input field for a token in the e-link tutorial
http://api-dev.freme-project.eu/doc/tutorials/getting-started-with-e-link.html#step-3-3-template-manipulation

However, I think its not clear for a user how to authenticate. The message says:

> Could not create resource: The anonymous user can not own any resource. You have to be logged in to create a resource.

1) users do not log in
2) no clear info on how they should log in -> provide info that they should get token and provide it in the input field at the end of the page
3) the input field for the token is hard to find. I would rather add token input field next to every API resources where authentication is needed.

**Comment by jnehring** [comment]
Moved to https://github.com/freme-project/technical-discussion/issues/114
