### ISSUE TITLE
Migrate to new architecture

### ISSUE THREAD

**Issue by jnehring** [freme-project/e-Link#68]

**Comment by ArneBinder** [comment]
see https://github.com/freme-project/e-services/tree/master/linking

TODO: 
* rename to "e-link"
* check for changes in the old e-Link project and migrate them

**Comment by ArneBinder** [comment]
DONE
@jnehring Should this repo be marked as depricated in any way?

**Comment by jnehring** [comment]
Thank you.

> @jnehring Should this repo be marked as depricated in any way?

We will do so when the migration is over.
