### ISSUE TITLE
Add languages for labels

### ISSUE THREAD

**Issue by x-fran** [freme-project/e-Link#71]
I implemented and tested the labels in one of our application.
Since is working only in English it will be nice to have it for the rest of the languages.

Thank you.

**Comment by m1ci** [comment]
> Since is working only in English it will be nice to have it for the rest of the languages.

Please provide list of languages? Thanks.

**Comment by x-fran** [comment]
All languages supported by FREME if possible. If not German, French, Spanish, Italian at least. Thanks.

**Comment by x-fran** [comment]
What's the status of this? Thanks

**Comment by jnehring** [comment]
We should gather WRIPL tasks and prioritize. There is also the other task of the wripl custom dataset. Which one is more important?

**Comment by x-fran** [comment]
Both have the same importance but let's do this first. Thanks

**Comment by jnehring** [comment]
Which datasets do you use for the labels? Only DBPedia or do you use other datasets also?

**Comment by x-fran** [comment]
For now DBPedia only. As far as I remember this feature works with DBPedia dataset only. Correct me if I'm wrong.

**Comment by jnehring** [comment]
Yes right now we only have the data for dbpedia.

**Comment by m1ci** [comment]
no active discussion, closing the issue.
